name: hitomemo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: 1.1.1
  app_review: 1.1.2
  apple_sign_in: ^0.1.0
  cloud_firestore: 0.13.3
  cloud_firestore_platform_interface: 1.0.0
  community_material_icon: 5.3.45
  connectivity: 0.4.8+6
  cupertino_icons: ^0.1.2
  device_preview: 0.4.5
  firebase_analytics: 5.0.11
  firebase_auth: 0.15.5+3
  firebase_dynamic_links: 0.5.0+11
  firebase_storage: 3.1.3
  firebase_crashlytics: 0.1.3+3
  # cache_image is GPL but it has 24 starts rather than firebase_image (5 starts)
  firebase_image: 0.1.6
  flutter_signin_button: ^1.0.0
  flutter_sticky_header: ^0.4.2
  font_awesome_flutter: 8.8.1
  freezed_annotation: 0.7.1
  google_sign_in: ^4.4.1
  http: 0.12.1
  i18n_extension: 1.4.1
  image_cropper: 1.2.3
  image_picker: 0.6.7+2
  intl: ^0.16.0
  launch_review: 2.0.0
  mecab_dart: 0.1.2
  multi_image_picker: 4.6.7
  # Getter not found: 'linux'
  # modal_bottom_sheet: 0.1.6+1
  path_provider: 1.6.11
  pedantic: 1.9.0
  photo_view: ^0.9.2
  provider: 4.1.3
  share: 0.6.4+1
  shared_preferences: 0.5.7+3
  sqflite: 1.3.1
  sticky_headers: ^0.1.8
  touch_indicator: 1.0.3 # This was not working when child elements catch the events
  tuple: ^1.0.3
  url_launcher: ^5.4.2
# Tests and etc. Not to be included in the release.
dev_dependencies:
  build_runner: 1.8.0
  cloud_firestore_mocks: 0.4.2
  firebase_auth_mocks: 0.1.2
  flutter_launcher_icons: ^0.7.4
  flutter_oss_licenses: 0.6.2 # flutter pub run flutter_oss_licenses:generate.dart
  flutter_test:
    sdk: flutter
  freezed: 0.10.9 # flutter pub pub run build_runner build --delete-conflicting-outputs
  mockito: ^4.1.1
  pedantic_mono: 1.8.0
  quiver: 2.1.3
  sqflite_ffi_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_ffi_test
  test: 1.14.7 # for beta channel

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
